version: '2.0'
services:
  database:
    image: postgres:alpine
#    volumes:
#    - db-data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    command: -c 'log_min_duration_statement=0' -c 'log_connections=on' -c 'log_destination=stderr' -c 'log_statement=all'
    environment:
    - POSTGRES_DB=example
    - POSTGRES_USER=example
    - POSTGRES_PASSWORD
  app:
    build: .
    restart: always
    ports:
    - "8080:8080"
    environment:
    - connStr="host=database user=example dbname=example password=${POSTGRES_PASSWORD} sslmode=disable"

#volumes:
#  db-data:
#    driver: local
